Repository inf112-v20/factoryRobots, pull requests merged in 2020-03, with the labels that each got.

#65 Use map as a singleton
  src/main/java/inf112/app/game/Application.java
  src/main/java/inf112/app/map/Map.java
  src/main/java/inf112/app/objects/Cog.java
  src/main/java/inf112/app/objects/Wall.java
Labels: enhancement

#75 Main menu buttons
  assets/game-menu.png
  assets/robo-rally-ui/PressStart2P-Regular.fnt
  assets/robo-rally-ui/Robo-Rally.atlas
  assets/robo-rally-ui/Robo-Rally.json
  assets/robo-rally-ui/Robo-Rally.png
  assets/robo_rally_logo.png
  pom.xml
  src/main/java/inf112/app/game/RoboRally.java
  src/main/java/inf112/app/objects/Player.java
  src/main/java/inf112/app/screens/MainMenuScreen.java
Labels: enhancement, graphics

#95 Change project structure
  src/main/java/inf112/app/cards/CardDeck.java
  src/main/java/inf112/app/cards/CardSlot.java
  src/main/java/inf112/app/cards/CardStatus.java
  src/main/java/inf112/app/cards/ICard.java
  src/main/java/inf112/app/cards/MoveCard.java
  src/main/java/inf112/app/cards/RotateCard.java
  src/main/java/inf112/app/game/CardUI.java
  src/main/java/inf112/app/game/Player.java
  src/main/java/inf112/app/game/RoboRally.java
  src/main/java/inf112/app/game/TiledMapActor.java
  src/main/java/inf112/app/game/TiledMapClickListener.java
  src/main/java/inf112/app/game/TiledMapStage.java
  src/main/java/inf112/app/map/Direction.java
  src/main/java/inf112/app/map/MapCell.java
  src/main/java/inf112/app/map/MapCellList.java
  src/main/java/inf112/app/map/Position.java
  src/main/java/inf112/app/objects/Cog.java
  src/main/java/inf112/app/objects/Conveyor.java
  src/main/java/inf112/app/objects/ILaserInteractor.java
  src/main/java/inf112/app/objects/Laser.java
  src/main/java/inf112/app/objects/Robot.java
  src/main/java/inf112/app/objects/Wall.java
  src/main/java/inf112/app/screens/GameScreen.java
  src/main/java/inf112/app/util/IDTranslator.java
  src/main/java/inf112/app/util/ObjectFactory.java
  src/test/java/inf112/app/cards/CardDeckTest.java
  src/test/java/inf112/app/cards/CardStatusTest.java
  src/test/java/inf112/app/cards/MoveCardTest.java
  src/test/java/inf112/app/cards/RotateCardTest.java
  src/test/java/inf112/app/game/PlayerTest.java
  src/test/java/inf112/app/map/MapCellListTest.java
  src/test/java/inf112/app/map/MapCellTest.java
  src/test/java/inf112/app/map/MapTest.java
  src/test/java/inf112/app/objects/ConveyorTest.java
  src/test/java/inf112/app/objects/DirectionTest.java
  src/test/java/inf112/app/objects/FlagTest.java
  src/test/java/inf112/app/objects/LaserTest.java
  src/test/java/inf112/app/objects/PositionTest.java
  src/test/java/inf112/app/objects/RepairStationTest.java
  src/test/java/inf112/app/objects/RobotTest.java
  src/test/java/inf112/app/objects/WallTest.java
  src/test/java/inf112/app/util/IDTranslatorTest.java
  src/test/java/inf112/app/util/ObjectFactoryTest.java
Labels: minor fix
